# Generated by Django 4.2.11 on 2024-04-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='slug',
            # Django would not accept migration unless a default was specified. No rows in database at this time.
            field=models.SlugField(default='placeholder-slug', max_length=200, unique=True),
        ),
    ]
