# Generated by Django 4.2.11 on 2024-05-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='updated_on',
            # Removed auto_now=True as manual workspace saving was needed for task updates.
            field=models.DateField(),
        ),
    ]
