# Generated by Django 4.2.11 on 2024-04-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspace_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
