# Generated by Django 4.2.11 on 2024-05-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_workspace_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='updated_on',
            field=models.DateField(null=True),
        ),
    ]
