# Generated by Django 4.2.11 on 2024-05-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_alter_task_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('TO-DO', 'To Do'), ('IN-PROGRESS', 'In Progress'), ('DONE', 'Completed')], default='MINOR'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor'), ('NICE-TO-HAVE', 'Nice to have!')], default='TO-DO'),
        ),
        migrations.AlterField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_tasks', to='workspace.workspace'),
        ),
    ]
