# Generated by Django 4.2.11 on 2024-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Critical', 'CRITICAL'), ('Major', 'MAJOR'), ('Minor', 'MINOR'), ('Nice to have!', 'NICE-TO-HAVE')], default='MINOR'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'TO-DO'), ('In Progress', 'IN-PROGRESS'), ('Completed', 'DONE')], default='TO-DO'),
        ),
    ]
