# Generated by Django 4.2.11 on 2024-05-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor'), ('NICE-TO-HAVE', 'Nice to have!')], default='MINOR'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO-DO', 'To Do'), ('IN-PROGRESS', 'In Progress'), ('DONE', 'Completed')], default='TO-DO'),
        ),
    ]
