# Generated by Django 4.2.11 on 2024-05-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor'), ('Nice to have!', 'Nice to have!')], default='MINOR'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='TO-DO'),
        ),
    ]
