# Generated by Django 4.2.11 on 2024-05-21 14:03

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', cloudinary.models.CloudinaryField(default='default_feature', max_length=255, verbose_name='image')),
                ('step', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(3)])),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(default='default_image', max_length=255, verbose_name='image')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', cloudinary.models.CloudinaryField(default='default_profile_image', max_length=255, verbose_name='image')),
                ('job_industry', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Aviation', 'Aviation'), ('Business Development', 'Business Development'), ('Communications', 'Communications'), ('Construction', 'Construction'), ('Education', 'Education'), ('Energy', 'Energy'), ('Engineering', 'Engineering'), ('Entertainment', 'Entertainment'), ('Fashion', 'Fashion'), ('Finance', 'Finance'), ('Food', 'Food'), ('Government', 'Government'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Human Resources', 'Human Resources'), ('Information Technology', 'Information Technology'), ('Insurance', 'Insurance'), ('Legal', 'Legal'), ('Manufacturing', 'Manufacturing'), ('Marketing', 'Marketing'), ('Military', 'Military'), ('Transportation', 'Transportation'), ('Other', 'Other')], default='other')),
                ('rating', models.CharField(choices=[('★☆☆☆☆', '★☆☆☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★★★☆☆', '★★★☆☆'), ('★★★★☆', '★★★★☆'), ('★★★★★', '★★★★★')], default='no rating', max_length=5)),
                ('review', models.TextField()),
                ('reviewed_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
