# Generated by Django 4.2.11 on 2024-04-15 11:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrum',
            name='file',
            field=cloudinary.models.CloudinaryField(default='scrum_manual', help_text='Download your Scrum manual here!', max_length=255, verbose_name='document'),
        ),
    ]
