# Generated by Django 4.2.11 on 2024-06-07 16:58

from django.db import migrations, models
from django.utils import timezone

def change_time_to_date(apps, schema_editor):
    Review = apps.get_model("scrum", "Review")
    for review in Review.objects.all():
        review.reviewed_on = review.reviewed_on.timezone.now().date()
        review.save()

class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(change_time_to_date),
        migrations.AlterField(
            model_name='review',
            name='reviewed_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
