# Generated by Django 4.2.11 on 2024-05-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_review_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile_image',
        ),
    ]
