# Generated by Django 4.2.11 on 2024-04-15 11:55

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_scrum_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', cloudinary.models.CloudinaryField(default='default_feature', max_length=255, verbose_name='image')),
                ('step', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(3)])),
                ('content', models.TextField()),
            ],
        ),
    ]
