# Generated by Django 4.2.11 on 2024-04-15 13:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0003_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrum',
            name='file',
            field=cloudinary.models.CloudinaryField(default='scrum_manual', help_text='Upload your Scrum manual here!', max_length=255, verbose_name='document'),
        ),
    ]
