# Generated by Django 4.2.11 on 2024-05-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0003_remove_review_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
