# Generated by Django 4.2.11 on 2024-04-17 12:46

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrum', '0004_alter_scrum_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', cloudinary.models.CloudinaryField(default='default_profile_image', max_length=255, verbose_name='image')),
                ('job_industry', models.TextField(choices=[('Agriculture', 'Agriculture'), ('Aviation', 'Aviation'), ('Business Development', 'Business Development'), ('Communications', 'Communications'), ('Construction', 'Construction'), ('Education', 'Education'), ('Energy', 'Energy'), ('Engineering', 'Engineering'), ('Entertainment', 'Entertainment'), ('Fashion', 'Fashion'), ('Finance', 'Finance'), ('Food', 'Food'), ('Government', 'Government'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Human Resources', 'Human Resources'), ('Information Technology', 'Information Technology'), ('Insurance', 'Insurance'), ('Legal', 'Legal'), ('Manufacturing', 'Manufacturing'), ('Marketing', 'Marketing'), ('Military', 'Military'), ('Transportation', 'Transportation'), ('Other', 'Other')], default='other')),
                ('rating', models.TextField(choices=[('Awful', '⭐🔘🔘🔘🔘'), ('Could be Better', '⭐⭐🔘🔘🔘'), ('Satisfactory', '⭐⭐⭐🔘🔘'), ('I like it!', '⭐⭐⭐⭐🔘'), ('Excellent!', '⭐⭐⭐⭐⭐')], default='no rating')),
                ('review', models.TextField()),
                ('reviewed_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
