# Generated by Django 4.2.11 on 2024-04-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.TextField(choices=[('⭐🔘🔘🔘🔘', '⭐🔘🔘🔘🔘'), ('⭐⭐🔘🔘🔘', '⭐⭐🔘🔘🔘'), ('⭐⭐⭐🔘🔘', '⭐⭐⭐🔘🔘'), ('⭐⭐⭐⭐🔘', '⭐⭐⭐⭐🔘'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], default='no rating'),
        ),
    ]
