# Generated by Django 4.2.11 on 2024-05-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrum',
            name='file',
        ),
    ]
